### ISSUE TITLE
Error on loading dashboard page

### ISSUE THREAD

**Issue by mg-i-alf-dan** [seriohub/velero-helm#18]
Hi all, i stay test this software, but i have a problem, when i land on dashboard page i get this error:
```
Service method
'data' - file name: stats_service.py - fn name: stats - line: 110
```

and the second error i get, is when i go on schedule page, i get this error:
```
Run Process Check Output Error
Error
```

i have tried to call the API with curl for test the APIs that this two pages use for retrive data.. but i get the same errors, someone can help me with this?

**Comment by davideserio** [comment]
Hi,
What does the diagnostic information on the login page show?

**Comment by mg-i-alf-dan** [comment]
![Screenshot_2024-05-15_10-41-10](https://github.com/seriohub/velero-helm/assets/163836599/57fe02d9-8cab-4c44-bd6a-b89aa394c5b6)

**Comment by mg-i-alf-dan** [comment]
i have already tried to substitute the Origin with "*", but the issue persist

**Comment by davideserio** [comment]
Which version of velero client and velero server are in use?

**Comment by mg-i-alf-dan** [comment]
Client: 1.13.0
Server: 1.13.1

Yes besides the dashboard and the schedules page, others pages works well

**Comment by nickveldrin** [comment]
Could this have something to do with the api not being authenticated or passing the authentication properly?

If i log in, I am able to click on the backup location and see my "default", but no other page shows me info.  

And then when i go to the debug shell and attempt to open an api location, every response comes back with "Not Authenticated".  On the "Response" part of the debug, i am showing a red error 400 on the pages with no data, while it's green 200 on the backup-location page that has data.

That stats api page mentioned by the OP is also showing red 400.
![velero 2024-05-15 053811](https://github.com/seriohub/velero-helm/assets/7116802/a4fe70ac-73be-48bd-ade5-49ca7404bbac)

**Comment by davideserio** [comment]
OK,

As mentioned in the README file, the project is currently running on clusters with version 12. We will be upgrading to version 13 shortly. There might be an update in the Velero client output JSON format. If anyone has the chance, please send me the output of the following commands so I can check for any differences with version 12 (please remove any sensitive information):

arduino
Copy code
velero schedule get -o json -n <your-velero-namespace>
and

arduino
Copy code
velero repo get -o json -n <your-velero-namespace>
I can then see if it's a formatting issue.

**Comment by mg-i-alf-dan** [comment]
velero schedule get -o json -n <your-velero-namespace>
```
{
  "kind": "Schedule",
  "apiVersion": "velero.io/v1",
  "metadata": {
    "name": "backup-daily-prd",
    "namespace": "velero",
    "uid": "8d64005c-28ba-44fc-8394-b3b4a89991e3",
    "resourceVersion": "147583966",
    "generation": 3,
    "creationTimestamp": "2024-05-14T10:28:34Z",
    "managedFields": [
      {
        "manager": "velero",
        "operation": "Update",
        "apiVersion": "velero.io/v1",
        "time": "2024-05-14T10:28:34Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:spec": {
            ".": {},
            "f:schedule": {},
            "f:template": {
              ".": {},
              "f:csiSnapshotTimeout": {},
              "f:defaultVolumesToFsBackup": {},
              "f:hooks": {},
              "f:includedNamespaces": {},
              "f:itemOperationTimeout": {},
              "f:metadata": {},
              "f:snapshotMoveData": {},
              "f:ttl": {}
            },
            "f:useOwnerReferencesInBackup": {}
          },
          "f:status": {}
        }
      },
      {
        "manager": "velero-server",
        "operation": "Update",
        "apiVersion": "velero.io/v1",
        "time": "2024-05-15T03:00:57Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:spec": {
            "f:skipImmediately": {}
          },
          "f:status": {
            "f:lastBackup": {},
            "f:phase": {}
          }
        }
      }
    ]
  },
  "spec": {
    "template": {
      "metadata": {},
      "includedNamespaces": [
        "*"
      ],
      "ttl": "0s",
      "hooks": {},
      "defaultVolumesToFsBackup": true,
      "csiSnapshotTimeout": "0s",
      "itemOperationTimeout": "0s",
      "snapshotMoveData": true
    },
    "schedule": "0 3 * * *",
    "useOwnerReferencesInBackup": false,
    "skipImmediately": false
  },
  "status": {
    "phase": "Enabled",
    "lastBackup": "2024-05-15T03:00:57Z"
  }
}
```

**Comment by davideserio** [comment]
The output JSON format is the same.
I did a other quick test, for version 13 you may need a cluster role update (current [cluster-role](https://github.com/seriohub/velero-helm/blob/main/chart/templates/21_cluster_role.yaml)), the following should work:
- create the clusterrole-patch.yaml file:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vui-mgmt-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - velero.io
  resources:
  - '*'
  verbs: 
  - '*'
```
- apply it
``` bash
kubectl patch clusterrole vui-mgmt-cluster-role --patch "$(cat clusterrole-patch.yaml)"
```
Please let me know if you encounter any problems or if the installation is successful.

**Comment by mg-i-alf-dan** [comment]
ok i have patched the cluster role,
now, Repositories page work,

Dashboard page give this error:
```
Service method
'data' - file name: stats_service.py - fn name: stats - line: 110
```

Schedules page give this error
```
Service method
'items' - file name: schedule_service.py - fn name: get - line: 23
```

**Comment by davideserio** [comment]
Hi,
I deployed on a cluster with velero version 13.2 with the patch and it works.
Can you verify that the patch was successful?
``` bash
kubectl get clusterrole vui-mgmt-cluster-role -o json
```
It shouldn't need to but can you try restarting the pod API as well?

**Comment by mg-i-alf-dan** [comment]
I reinstalled everything from scratch, and applied the patch, from the api pod logs I still get the code 400, I installed velero 1.13.2, to be the same as your implementation, I attach images

![Screenshot_2024-05-15_16-05-30](https://github.com/seriohub/velero-helm/assets/163836599/36588203-aec2-40e1-9efb-a0a5d6a55555)

![Screenshot_2024-05-15_16-05-53](https://github.com/seriohub/velero-helm/assets/163836599/f08d2f20-1171-494a-a3d0-5042e7f2d848)

![Screenshot_2024-05-15_16-06-54](https://github.com/seriohub/velero-helm/assets/163836599/63bb7598-0ebf-442b-b0ed-94791ff21a9e)

**Comment by mg-i-alf-dan** [comment]
This is the actual status of cluster role

```
{
    "apiVersion": "rbac.authorization.k8s.io/v1",
    "kind": "ClusterRole",
    "metadata": {
        "annotations": {
            "meta.helm.sh/release-name": "vui",
            "meta.helm.sh/release-namespace": "velero"
        },
        "creationTimestamp": "2024-05-15T14:04:06Z",
        "labels": {
            "app.kubernetes.io/instance": "vui",
            "app.kubernetes.io/managed-by": "Helm",
            "app.kubernetes.io/name": "vui",
            "app.kubernetes.io/version": "0.1.7",
            "helm.sh/chart": "vui-0.1.7"
        },
        "name": "vui-mgmt-cluster-role",
        "resourceVersion": "148013842",
        "uid": "9f71cbc8-22cf-4e6f-b91f-e5fd031b7eb1"
    },
    "rules": [
        {
            "apiGroups": [
                ""
            ],
            "resources": [
                "namespaces"
            ],
            "verbs": [
                "get",
                "list"
            ]
        },
        {
            "apiGroups": [
                "storage.k8s.io"
            ],
            "resources": [
                "storageclasses"
            ],
            "verbs": [
                "list"
            ]
        },
        {
            "apiGroups": [
                ""
            ],
            "resources": [
                "nodes"
            ],
            "verbs": [
                "get",
                "watch",
                "list"
            ]
        },
        {
            "apiGroups": [
                "velero.io"
            ],
            "resources": [
                "*"
            ],
            "verbs": [
                "*"
            ]
        }
    ]
}
```

**Comment by davideserio** [comment]
Could you please try running these commands from within the API pod bash and let me know if they are successful?

``` bash
velero schedule get -o json
```
``` bash
velero repo get -o json
```

Please verify that the first line is respectively 

- "kind": "ScheduleList" 

and 

- "kind": "BackupRepositoryList"

**Comment by mg-i-alf-dan** [comment]
My result is:

- "kind": "Schedule”

and

- "kind": "BackupRepositoryList"

**Comment by mg-i-alf-dan** [comment]
Your comment gave me an idea and I did a test, and it works, but if there is only one schedule in the schedule, it doesn't create the overlying object (ScheduleList) so the UI doesn't find the object, it should be fixed on the ui, I think it also applies to backup and repo,

Thanks for your help

**Comment by nickveldrin** [comment]
For me, the clusterrole was "velero-ui-vui-mgmt-cluster-role", and when i applied the patch from above, it fixed all my dashboard issues.
